config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users

  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all
    can :manage, Book do |book|
      book.try(:user) == user
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :sales

  has_attached_file :image
  has_attached_file :resource

  validates_attachment_content_type :image, content_type:  /^image\/(png|gif|jpeg)/,
                                            message: "Only images allowed"

  validates_attachment_content_type :resource, content_type: ['application/pdf'],
                                               message: "Only pdfs allowed"

  validates :image, attachment_presence: true
  validates :resource, attachment_presence: true

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :book

  before_create :generate_guid

  include AASM

  aasm column: :state do
    state :pending, initial: true
    state :processing
    state :finished
    state :errored

    event :process do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end

  end

  def charge!
    save!
    process!
    finish!
  end

  protected

  def generate_guid
    self.guid ||= SecureRandom.uuid
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: 'You are unauthorized.'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @books = Book.where(availability: true)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
    authorize! :manage, @book
  end

  def create
    @book = current_user.books.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private

  def set_book
    @book = Book.friendly.find(params[:id])
  end


  def book_params
    params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
    redirect_to books_path if current_user
    @books = Book.last(4)
  end

  def dashboard
    @books = current_user.books
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    book = Book.find_by(slug: params[:slug])
    sale = book.sales.create(
      amount: book.price,
      buyer_email: current_user.email,
      seller_email: book.user.email
    )
    sale.charge!

    if sale.finished?
      redirect_to pickup_path(guid: sale.guid), notice: 'success!'
    else
      redirect_to book_path(book), 'something went wrong'
    end
  end

  def pickup
    @sale = Sale.find_by(guid: params[:guid])
    @book = @sale.book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.haml
.col-md-3
  .thumbnail
    = link_to book_path(book) do
      = image_tag book.image(:original), class: 'image-responsive'
  .caption
    %p
      %strong= link_to book.name, book_path(book)
    %p
      $
      = book.price.to_f / 100

app/views/books/_form.html.haml
= simple_form_for @book, html: { class: 'user-form' } do |f|
  %h2= title
  = f.error_notification

  .form-inputs
    = f.input :name, required: true, label: false, placeholder: 'Name', input_html: { class: 'form-control' }
    = f.input :author, required: true, label: false, placeholder: 'Author', input_html: { class: 'form-control' }
    = f.input :description, label: false, placeholder: 'Description', input_html: { class: 'form-control' }
    = f.input :price, label: false, placeholder: 'Price', input_html: { class: 'form-control' }
    = f.input :image
    = f.input :resource

    .checkbox.text-center
      = f.input :availability
  .form-actions
    = f.button :submit, class: 'btn btn-primary btn-block'

app/views/books/edit.html.haml
= render 'form', title: 'Editing Book'

%p
  = link_to 'Show', @book
  |
  = link_to 'Back', books_path

app/views/books/index.html.haml
.row
  = render @books

app/views/books/new.html.haml
= render 'form', title: 'New Book'

%p= link_to 'Back', books_path

app/views/books/show.html.haml
.row
  .col-md-6
    = image_tag @book.image(:original), class: 'img-responsive'
  .col-md-6
    %h3
      = @book.name
      by
      = @book.author
    %p.justify= @book.description
    %h4
      $
      = @book.price.to_f / 100

= link_to 'Edit', edit_book_path(@book)
= link_to 'Back', :back

- if current_user
  = form_for @book.sales.new, url: buy_path(slug: @book.slug) do |f|
    %button.btn.btn-primary.btn-lg BUY

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{ role: :navigation }
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "estuk", root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Books", books_path
        - if current_user
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Dashboard", dashboard_path
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path
        %li

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Estuk
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'layouts/header'
    .container
      - flash.each do |type, message|
        .alert.alert-info
          = message
      = yield

app/views/pages/_books.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th ID
      %th Name
      %th Available?
      %th &nbsp;
  %tbody
    - @books.each do |book|
      %tr
        %td= book.id
        %td= link_to book.name, book_path(book)
        %td= book.availability
        %td= link_to 'Edit', edit_book_path(book)

app/views/pages/_purchased.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Date
      %th Seller
  %tbody
    - @purchased.each do |sale|
      %tr
        %td= link_to sale.book.name, pickup_path(guid: sale.guid)
        %td= time_ago_in_words(sale.created_at)
        %td= sale.seller_email

app/views/pages/_sales.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Date
      %th Buyer
  %tbody
    - @sales.each do |sale|
      %tr
        %td= link_to sale.book.name, pickup_path(guid: sale.guid)
        %td= time_ago_in_words(sale.created_at)
        %td= sale.buyer_email

app/views/pages/dashboard.html.haml
.container
  .row
    %h1 Dashboard
    = link_to 'New Book', new_book_path, class: 'btn btn-primary btn-sm'
    .clearfix
    .col-md-4
      %h4 Books
      = render 'books'
    .col-md-4
      %h4 Purchased
      = render 'purchased'
    .col-md-4
      %h4 Sales
      = render 'sales'

app/views/pages/home.html.haml
.jumbotron
  %h1 Welcome to our store
  = link_to 'Books', books_path, class: 'btn btn-primary btn-block'
  = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-block'

.row
  = render @books

app/views/transactions/pickup.html.haml
.row.text-center
  %h1
    Congratulations on your order
    = @sale.guid
  %p
    Here is your download link:
    = link_to 'Download', @book.resource.url